from __future__ import annotations

import os
from pathlib import Path


APP_DIR_NAME = "clicourier"


def xdg_config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", "~/.config")).expanduser()


def xdg_state_home() -> Path:
    return Path(os.environ.get("XDG_STATE_HOME", "~/.local/state")).expanduser()


def xdg_data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME", "~/.local/share")).expanduser()


def default_config_dir() -> Path:
    return xdg_config_home() / APP_DIR_NAME


def default_state_dir() -> Path:
    return xdg_state_home() / APP_DIR_NAME


def default_data_dir() -> Path:
    return xdg_data_home() / APP_DIR_NAME


def default_config_path() -> Path:
    return default_config_dir() / "config.env"


def default_pid_path() -> Path:
    return default_state_dir() / "clicourier.pid"


def default_log_path() -> Path:
    return default_state_dir() / "clicourier.log"


def default_mute_file() -> Path:
    return default_state_dir() / "muted"


def default_whisper_dir() -> Path:
    return default_data_dir() / "whisper.cpp"


def ensure_private_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        path.parent.chmod(0o700)
    except PermissionError:
        pass


def quote_env_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def write_env_file(path: Path, values: dict[str, str]) -> None:
    ensure_private_parent(path)
    lines = [
        "# CliCourier local configuration",
        "# Generated by `clicourier setup`.",
        "",
    ]
    for key, value in values.items():
        lines.append(f"{key}={quote_env_value(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except PermissionError:
        pass

